logging:
    file:
        max-history: 24
        max-size: 100mb
        name: /logapp/log/batch.log

    level:
        root: info

    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) [%thread] %clr(%logger){cyan}
            : %msg%n'
        file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n'

spring:
    output:
        ansi:
            enabled: ALWAYS
